[supervisord]
nodaemon=true
user=openclaw
logfile=/dev/stdout
logfile_maxbytes=0

[program:dashboard]
command=node /app/dist/index.mjs dashboard
user=openclaw
environment=
    CLAW_PILOT_ENV="docker",
    XDG_RUNTIME_DIR="/run/user/1000",
    NODE_ENV="development"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
