// src/core/nginx-generator.ts

export interface NginxOptions {
  slug: string;
  domain: string;
  port: number;
  certPath: string;
  keyPath: string;
}

export function generateNginxVhost(options: NginxOptions): string {
  const { slug, domain, port, certPath, keyPath } = options;

  return `# Nginx vhost for OpenClaw instance: ${slug}
# Generated by claw-pilot

server {
    listen 80;
    server_name ${domain};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ${domain};

    ssl_certificate     ${certPath};
    ssl_certificate_key ${keyPath};

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Proxy to OpenClaw gateway
    location / {
        proxy_pass         http://127.0.0.1:${port};
        proxy_http_version 1.1;

        # WebSocket support
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";

        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }
}
`;
}
